# General
name: baseline
output_folder: ./results
# results_dir:
# log_dir:

# Training data
training_jsons: [prepare_IAM_Lines/raw_gts/lines/txt/training.json]
training_root: "./data"
training_suffle: true

# Testing data
testing_jsons: [prepare_IAM_Lines/raw_gts/lines/txt/test.json]
testing_root: "./data"
testing_suffle: false

#Network
TESTING: True
batch_size: 8               # Batch size
input_height: 60            # Input dimension of image (will be cropped by default?)
cnn_out_size: 1024          # Output dimension of CNN
learning_rate: .0001
dropout: 0.5                 # Probability of being "dropped out"
embedding_size: 32           # The size of the embedding layer in the MLP
writer_rnn_output_size: 256  # LSTM output dimension for writer classifier
num_of_channels: 3

# Options
warp: false
